# Generated by Django 2.0.1 on 2018-01-04 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mathstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_answer', models.CharField(choices=[('a', 3), ('b', 4), ('c', 5), ('d', 6)], max_length=50)),
                ('right_answer', models.IntegerField()),
                ('was_correct', models.BooleanField()),
                ('question', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathstack.Student')),
            ],
        ),
    ]
