# Generated by Django 2.0.1 on 2018-01-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathstack', '0002_auto_20180104_1348'),
        ('multiplechoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathstack.Student')),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='answer4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='raw_answer',
            field=models.CharField(choices=[('a', models.IntegerField()), ('b', models.IntegerField()), ('c', models.IntegerField()), ('d', models.IntegerField())], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='activemultiplechoicequestion',
            unique_together={('student', 'q_text')},
        ),
    ]
