# Generated by Django 2.0.1 on 2018-01-04 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('multiplechoice', '0003_auto_20180104_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='raw_answer',
            field=models.IntegerField(choices=[(0, 0), (0, 0), (150, 150), (0, 0)], max_length=50),
        ),
    ]
